[rabbitmq]
protocol="http"
host="192.168.0.1"
port="15672"
username="the_username"
password="the_password"
vhost="%2f"

[settings]
poll_seconds=60 # how often to check
alert_expire_seconds=600 # when does a sent alert expire and thus can be resent again

[slack]
webhook_url="https://hooks.slack.com/services/xxx/xxxx"
channel="the_slack_channel_name"
screen_name="RabbitMQ"

[[triggers]]
type = "messages_ready" # possible values are consumers_total, memory_total, messages_total, messages_ready, messages_unacknowledged
threshold = 10000
queue = "the_queue_name" # this is optional, if ommitted it will be a rule valid for all queues

[[triggers]]
type = "consumers_total"
threshold = 100
# since queue is missing, this is a global rule for all queues