on:
  push:
    tags:
      - '*.*.*'

name: Docker
jobs:
  build:
      name: Build and publish Docker image
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@master
        - name: Build Docker image and push to Docker Hub
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
            repository: zbrox/rmq_monitor
            tags: latest
            tag_with_ref: true
            push: true